### PR TITLE
Bug fix - Sniping from pokezz fixed after pokezz implementation change

### PR DESCRIPTION
**Pull request by jjskuld**
## Short Description:
Fixes pokezz sniping when pokezz website is down.   Currently, if pokezz is not responding, then the bot will just do nothing when it starts to snipe.  It just waits indefinitely.

Now I've added a 5 second timeout, so that bot continues along if pokezz is not responding within 5 seconds.

### CODE REVIEW

**Comment by jjskuld** [comment]
I just noticed that the reason Pokezz was causing the bot to hang was that they changed their implementation (no longer using JSON).  So I fixed the code so that Pokezz is working again.

**Comment by slyfoxjosh** [comment]
Does this fix require that i download a newer version again or is it like a server side fix on your end?

**Comment by MrPK2710** [comment]
what i do with it ?

**Comment by MrPK2710** [comment]
Got it" Work know man! thx

**Comment by Kozartu** [comment]
how to use this?

**Pull request merged**
