### PR TITLE
[Feature] Automatic Translation Detection

### PR DESCRIPTION
**Pull request by Andrerm124**
Added a new method to pull the system translation when new configs are created. It will then ask the user if they would like to enter a new language code (And then build the config)

### CODE REVIEW

**Comment by Andrerm124** [comment]
**I MUST WARN**

Due to how this has performed inline session swapping, it MAY be deemed unsafe. I would recommend more advanced devs to revisit this at some point.

**Comment by Andrerm124** [comment]
Do not commit, seems authentication is failing. Possibly because of this commit.

**Comment by Oolaruu** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/2336

**Comment by AndreasGilja** [comment]
Necrobot does not woork


Sendt fra min iPhone

Den 4. aug. 2016 kl. 00.16 skrev Oolaruu <notifications@github.com<mailto:notifications@github.com>>:


https://github.com/NECROBOTIO/NecroBot/issues/2336

-

**Comment by simplyphp** [comment]
This branch has conflicts that must be resolved

**Pull request closed without merging**
