### PR TITLE
[Feature] Sniping pokemon missing from the pokedex

### PR DESCRIPTION
**Pull request by ChemiHatake**
now players will be able to choose if they want the sniper to snipe pokemon missing from their pokedex without adding those pokemon to the sniper filter list.
(by changing 'SnipePokemonNotInPokedex' to true)

REQUEST: #2042

### CODE REVIEW

**Comment by simplyphp** [comment]
[DO NOT MERGE THIS UNTIL API FIX IS IN AND THIS CAN BE VERIFIED WORKING]

**Comment by ChemiHatake** [comment]
well it is working, I tested it by printing the list of the pokemon to snipe with the setting on and off with a player with all the pokemon and one without any.

I haven't changed anything about the sniping itself, just the list of the pokemon to snipe.

**Comment by ijolumoet** [comment]
No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by ijolumoet** [comment]
No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by Bitschi** [comment]
Same here. Cant use the Bot

**Comment by santosh61** [comment]
HELP!!!No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by Manjar12** [comment]
yes, me to,No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by ChemiHatake** [comment]
guys the bot isn't working for everyone right now, 
there's a problem with the API and it will be probably fixed soon.

**Comment by pwnyprod** [comment]
All that stupid people here who cry for help and wont read any shit on the Readme... I hate that DAU's

**Comment by Wiggiii** [comment]
The necrobot for pokemon go doesn't work for me at all, it says that there is no pokestops in the area, can someone please help or will we get a updated version?

**Comment by ChemiHatake** [comment]
PLEASE READ THE README.MD 
its called readme for a reason

**Comment by kevinduvan98** [comment]
Hi! I'm Colombian and I speak so so english. I want to know what is that you do please. A PokémonGo Bot? You can send me more information? I appreciate it. Thank you for all. :)

**Comment by Kekzy** [comment]
i am not sure if the pokedex way will work, i guess i tried it before and its just lists pokemon seen and caught, but not unknown pokemons

**Comment by mct43969** [comment]
I like this! I'm trying to catch all 145 Pokémon, but with dozens of BOT instances, I can't edit all the "PokemonsToIgnore" in each config or the "PokemonsTransferFilter"

**Comment by ChemiHatake** [comment]
@Kekzy Yes, if the pokemon was not seen/caught, the PokedexEntry equals null.
that's why I made a generic list out of the pokemonId enum values, and extracted the
list of the captured pokemon out of it.

**Comment by ChemiHatake** [comment]
Ill reopen a pull request

**Pull request closed without merging**
