### PR TITLE
Updating IV and CP logic for transferring.

### PR DESCRIPTION
**Pull request by dddbliss**
When choosing Pokemon to transfer, if IV, then keep highest CP - if CP, keep highest IV.

### CODE REVIEW

**Comment by Silverarrows1986** [comment]
come on i need this :(

**Comment by Silverarrows1986** [comment]
or something to choose  

"PrioritizeIvOverCp": true,
"PrioritizeAfterIvByCpOrStamina": "cp", 

dunno if its possible to do

**Comment by dddbliss** [comment]
Relax, the PR is still open.

**Comment by Algent** [comment]
Awesome, is there any way you could also (In another PR maybe ?) add an option to keep both best IV and best CP unless it the same pokemon ?

**Pull request merged**
