### PR TITLE
Add Highests Pokemo Header And Cell Translation

### PR DESCRIPTION
**Pull request by TCCinTaiwan**
try to fix
#5089
#5100

### CODE REVIEW

**Comment by GrimmGringo** [comment]
You have to add those new translations to every translation file before we can merge this. Leaving them as English is fine, so others can translate them, but they need to be in every translation file first.

**Comment by TCCinTaiwan** [comment]
about https://github.com/NECROBOTIO/NecroBot/pull/5106#issuecomment-239201962
Did you mean add  { "Key": "HighestsPokemoHeader", "Value": "====== {0} ======" }, { "Key": "HighestsPokemoCell", "Value": "# CP {0}/{1} | ({2}% {3})\t| Lvl {5}\t {6}: {7}\t {8}: {9} {10}: {11} {12}: {13}" } to every single translation json file.

**Comment by GrimmGringo** [comment]
Verify that you can use English and German languages without any issue please.

**Comment by TCCinTaiwan** [comment]
# Add Proxy and HighestsPokemo
Proxied
FixProxySettings
Unproxied
HighestsPokemoHeader
HighestsPokemoCell

**Pull request merged**
