### PR TITLE
translation fix as requested

### PR DESCRIPTION
**Pull request by davegranlet**
kurvex - Today at 6:33 PM
@GrimmGringo on ES translate, add on lane 527 an ",". it's giving an error that makes it cannot load it
😃
GrimmGringo - Today at 6:36 PM
Someone submit a pr
I'm not home
Thx

### CODE REVIEW

**Comment by GrimmGringo** [comment]
This fails to build, please double check

**Comment by Cyrus-Wong** [comment]
I don't know where and how to report errors/bugs, using 0.7.5 but still having the red wall of words, anyone?

untitled

untitled1

**Comment by davegranlet** [comment]
I'm not sure why it's failing litterally it's just a "'" added on line 526

**Comment by 963963abc** [comment]
[08:20:06] (ATTENTION) No usable PokeStops found in your area. Is your maximum d
istance too small?

**Pull request closed without merging**
