### PR TITLE
Better [it] translation

### PR DESCRIPTION
**Pull request by theparcel**

### CODE REVIEW

**Comment by AlessioDP** [comment]
Merge it into https://github.com/NECROBOTIO/NecroBot/pull/3092

**Comment by GrimmGringo** [comment]
This branch has conflicts that must be resolved

**Comment by 20giis** [comment]
hey why has the issue section been closed down? Necrobot won't move.. why is this?

**Comment by GrimmGringo** [comment]
This branch has conflicts that must be resolved

**Pull request closed without merging**
