### PR TITLE
Update .gitmodules to use directly original FeroxRev api and not forks

### PR DESCRIPTION
**Pull request by hilycker**
Update .gitmodules to use directly original FeroxRev api and not forks

### CODE REVIEW

**Comment by simplyphp** [comment]
This will not work because FeroxRev API does not have the changes yamashi wrote.

**Comment by simplyphp** [comment]
Just saw that they actually did merge it in, re-opening.

**Comment by simplyphp** [comment]
[DO NOT MERGE THIS YET]

**Comment by dddbliss** [comment]
Merging into our own for a while until Ferox can fix csproj related issues.

**Pull request closed without merging**
