### PR TITLE
updated translation.de.json

### PR DESCRIPTION
**Pull request by somani6**
added trnaslation for waitingForMorePokemonToEvolve

### CODE REVIEW

**Comment by Draniella** [comment]
its not working anymore for me, it just start to search for pokestops, but it wont find.....and i already check the coords, and there is pokestops there!! i dunno what to do, help :c 

the version is 0.6.4

**Comment by somani6** [comment]
@Draniella this has nothing to do with my pull request :) Bot API is broken at this time due to some major changes by Niantic.
The API Core Dev Team is working on this issue. https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

**Comment by Draniella** [comment]
im sorry and ty for telling me <3

**Comment by fr3k4life** [comment]
@somani6, btw. Pokémon ist sowohl Singular und Plural.

**Comment by somani6** [comment]
@fr3k4life :) thx, done

**Pull request merged**
