### PR TITLE
Disable the bot untill we can figure out what is causing the bans.

### PR DESCRIPTION
**Pull request by Markersx**
Hopefully this will save some people from getting banned.

### CODE REVIEW

**Comment by NeCx** [comment]
Haha

**Comment by letplay888** [comment]
may i know how to find the KillSwitch.txt file and amend, thank you.

**Comment by boXseven** [comment]
yeah do it :D

**Comment by aguslaco** [comment]
I'm getting the message that the servers are down, is there any way to remove the ban from that account?

**Comment by jnlawrence** [comment]
Someone help me please. Keeps on crashing and displays this code

[20:41:38] () Exception caught, writing LogBuffer.

Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'PokemonGo.RocketAPI.HttpClient.PokemonHttpClient' threw an exception. ---> Sy
stem.TypeLoadException: Could not load type 'System.Security.Authentication.SslP
rotocols' from assembly 'System.Net.Primitives, Version=4.0.0.0, Culture=neutral
, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Net.Http.HttpClientHandler..ctor()
   at PokemonGo.RocketAPI.HttpClient.PokemonHttpClient..cctor()
   --- End of inner exception stack trace ---
   at PokemonGo.RocketAPI.HttpClient.PokemonHttpClient..ctor()
   at PokemonGo.RocketAPI.Client..ctor(ISettings settings, IApiFailureStrategy a
piFailureStrategy)
   at PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings
 logicSettings)
   at PoGo.NecroBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings
 logicSettings)
   at PoGo.NecroBot.CLI.Program.Main(String[] args)

**Comment by dakeeper** [comment]
Same problem here with the Log Exeption. Any suggestions?

**Comment by crinq98** [comment]
http://go.microsoft.com/fwlink/?LinkId=780597 download this for the exception

**Comment by athena93** [comment]
is there anyone still running the bot? or just me? is it safe ?

**Comment by sidneynxavier** [comment]
Hello all... I have the message : Failed to get data game from the server. Is this could be any type of ban? 
I used another acount and its working fine..
Any Idea?

Thanks..

**Comment by SatriaZoeda** [comment]
Where to put code..???
Killswitch...??
newbie plz......

**Comment by shu90** [comment]
@sidneynxavier  I will not assume it is a ban, because sometime I can login just fine with my main account.. also 1 of my account that I'm not using bot get that message when I'm trying to log in.. other 2 of my account also using bot can log in just fine.. try refer to pokemon go server of your country.. maybe that's the problem..

**Comment by Dexter145** [comment]
Bot still works fine over here.

**Comment by vipery** [comment]
ben

**Comment by MarkyD1986** [comment]
latest release crashes instantly on startup 

with an error starting like this,

Unhandled Exception: System.TypeInitializationException

**Comment by sidneynxavier** [comment]
@shu90
Thanks for the helping.
Well... I'm still trying to login..but the mesagge is the same... I will wait more time to see what the server will do
For other side... I will try to login using another country....

**Comment by kkdvka** [comment]
I have a problem and I don't know what is going on, I can play the game and I can catch pokemon but I can't spin pokestops, always says "Try again later", is this a kind of ban? Help me please

**Comment by githubusernam** [comment]
I can login, it spins pokestops and works. also snipes.
but every pokemon I run into, including the snipes, flees.

**Comment by psblackz** [comment]
yes same...

**Comment by Bdgi7665** [comment]
chrysanthemum -
This always pops up when I'm trying to open up Necrobot, i havent changed things in config or auth and never opened the new config app. Anyone else having this problem?

**Comment by psblackz** [comment]
i have one acc that works other not.. this acc cant snipe pokestops or pokemon.. perm ban ?

**Comment by thommy92** [comment]
Hello,
I stopped all use of necrobot this morning.
The "softban" after 45 trials apparently not. That same with my smartphone.
Have they found a way to softban? :/
Sorry for my English

**Comment by aguslaco** [comment]
**I need help with this, does anyone know what does it mean? I can log in fine with other accounts.**


 Pokemon Servers might be offline / unstable. Trying again...
[08:25:40] Error: System.NullReferenceException: Object reference not set to an instance of an object.
at PoGo.NecroBot.Logic.Inventory.<GetPokemons>d__34.M oveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowF orNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.Handle NonSuccessAndDebuggerNotification(Task task)
at PoGo.NecroBot.Logic.Inventory.<GetHighestsCp>d__22 .MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowF orNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.Handle NonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.Valida teEnd(Task task)
at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask. <Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowF orNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.Handle NonSuccessAndDebuggerNotification(Task task)
at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0. MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowF orNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.Handle NonSuccessAndDebuggerNotification(Task task)
at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3 .MoveNext()

**Comment by gorrioncillo** [comment]
please, someone with the release 0.8.6 but for net 4.5.2, this is because i can't install the net 4.6.2, it ask me for win updates which i can't (should't) do. PLEASE

**Comment by prakosodio** [comment]
Same problem i can spin the pokestop but i cant catch pokemon, including ratata cp 10, it always flees, can anyone know the problem? Is it ban ?

**Comment by jonsnowssnorlax** [comment]
I'm having the same issue. Also it looks like they are deleting all the issues relating to this new type of ban. Google issue 5304 and look a the google cached page. There are tons like it that have since been deleted.

**Comment by fuckNIANTIC** [comment]
Stop using bots for awhile, 3/10 of my accounts has been banned. When you get ban your login loading screen while show 'failed to retrieve player data', not the page where it says server problems with various Pokemon on the background, becareful

**Comment by majdak79** [comment]
just do the killswitch :-)

**Comment by fuckNIANTIC** [comment]
I'm hoping someone can do a reverse engineering for the ban (reverse ban) if possible before they really trash all the data. It seems now to be a semi-perm ban if that's a thing

**Comment by artwasme9** [comment]
I am also cant catch any pokemon but I can get items in pokestops. Am I
banned?

**Comment by majdak79** [comment]
everyone was expecting this for days. the cheater accounts are trash now.

**Comment by kkdvka** [comment]
@prakosodio I have the same problem but at reverse.. I can catch pokemon but I can't spin pokestop.. @fuckNIANTIC Do you think it is a kind of perm ban? It's so annoying!

**Comment by jambogvg** [comment]
Hi all,
I'm having this problem since 10:00 A.M. ; could this be a ban? I can't access from my iphone 5 iOS 8.4 jailbroken, it blocks on gyrados's loading screen and tells me : "Unable to retrieve the game data from the server".
bug

**Comment by fuckNIANTIC** [comment]
If you can login your account, but can't see Pokéstop. Or gym you are softban, if you can't login successfully to the game than most likely ur banned, it's fucking stupid how Niantic set the experience so high to achieve cap level. Now since I don't have a 40 account I will be competing with those that have 38-40. My wish is Niantic just ban accounts level 35 or higher

**Comment by prakosodio** [comment]
But my friends just begin to play pogo, he is new player, its like the same problem, he cant login the pogo... there is many different problem in here ~~

Sorry for my bad english

**Comment by aguslaco** [comment]
@jambogvg I'm having the same problem, I think it's a permaban. We have to wait out and see what happens.

**Comment by fuckNIANTIC** [comment]
An example of the ban 

image

**Comment by lucky4com** [comment]
read this 
https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308-Submit-a-ban-appeal

**Comment by ciblnt** [comment]
Mines a little different. I was having the same issues as other people last night. I could catch pokemon, but it kept telling me i was softbanned at pokestops. So I waited until this morning and got in my car and went try it on my phone. I can catch pokemon just fine. I can gym battle just fine. I can add pokemon to gyms just fine. But everytime i try to spin a pokestop it tells me Please Try Again Later. Its like EVERYTHING is working just fine but i can't spin pokestops. Necrobot was doing the same thing yesterday afternoon. I waited until night time, tried again, and the same thing. Now its happening the same thing but on my phone.

**Pull request closed without merging**
