### PR TITLE
Fixed assembly / Translation issue after #2755

### PR DESCRIPTION
**Pull request by somani6**
I updated all translations files by changing EventPokemonCapture to
EventPokemonCaptureSuccessSuccess i did NOT translate them, i don't
speak most of these langauges :)

### CODE REVIEW

**Comment by GrimmGringo** [comment]
This branch has conflicts that must be resolved

**Comment by somani6** [comment]
should be resolved

**Comment by ChemiHatake** [comment]
this is not updated at all

**Comment by somani6** [comment]
@ChemiHatake thats because it was pulled to 0.7.1 ..

**Comment by somani6** [comment]
close this, since #2941 is newer and reffers to 0.7.1 - this pull goes to 0.7.1

**Pull request closed without merging**
