### PR TITLE
Add alert for Pokémon type, CP or IV

### PR DESCRIPTION
**Pull request by PiscisSwimeatus**

### CODE REVIEW

**Comment by GrimmGringo** [comment]
I personally don't see the need for this?

**Comment by cawk** [comment]
neither do i 
why would someone want to use this?

**Comment by rahulrverma** [comment]
Alert sound for errors or when the bot asks to key press would be a better addition. :)

**Comment by PiscisSwimeatus** [comment]
Well I think its a good addition hence why I made it ;) It makes it so much easier to catch those IV 100 without needing to watch the console all the time.

**Comment by NecronomiconCoding** [comment]
After a discussion with the Dev Team we have to decline that PR

**Pull request closed without merging**
