### PR TITLE
Added multiple usability improvements

### PR DESCRIPTION
**Pull request by Andrerm124**
_Resubmitted #2711 with fresh clone_

**CHANGELOG:**
- Added a new method to pull the system translation when new configs are created. It will then ask the user if they would like to enter a new language code (And then build the config)

- Now asks the user if they would like to download/install a new update (When there is one) and will display any new options added in the version.

- Implemented functions to allow for the translation of pokemon moves

- If the user is updating the bot and new options are added, ask the user if they would like to open the config file to view the new additions.

- Added a low level killswitch to disable the bot and print a notification for the reason. This is only for situations whereby the bot may be broken. **This was made extremely quickly and I believe there should be better implementation of this idea**

_This commit has been tested by only two users, one on an english system, another on a french system. Multiple logical processes were tested however there may still be issues to be found_

**Credits to @Oolaruu for the ideas**

### CODE REVIEW

**Comment by simplyphp** [comment]
This branch has conflicts that must be resolved

**Comment by simplyphp** [comment]
Also, you will have to change Program.cs from:
        private static string strKillSwitchUri =
            "https://raw.githubusercontent.com/Andrerm124/NecroBot/master/KillSwitch.txt";

To:
        private static string strKillSwitchUri =
            "https://raw.githubusercontent.com/NECROBOTIO/NecroBot/master/KillSwitch.txt";

**Comment by Oolaruu** [comment]
What about all the translation files I have submitted ?
Need to revert it ?

**Comment by Andrerm124** [comment]
No it'll be fine. I uploaded the French translation forgetting that you'd already done it. I'll fix this up when I get home

**Comment by Oolaruu** [comment]
About the french language, still need few more hours, i'll update it myself.

**Pull request merged**
