### PR TITLE
Fixed Language Code (changed translation file name)

### PR DESCRIPTION
**Pull request by Oolaruu**
**Fixed language code in translation file name:**
gr --> el Greek
nl  --> nl-NL Dutch
no  --> nn-NO Norwegian
pt-br --> pt-BR  Portuguese (Brazil)
pt-pt --> pt-PT Portuguese (Portugal)
ru_RU --> ru-RU  Russian (Russia)
uk_UA --> uk-UA Ukranian
zh_CN --> zh-CN Chinese
zh-CN_pp
zh_tw --> zh-TW  Chinese (Taiwan)

**Fixed missing translation file not generated after first use:**
kh, zh-CN_pp, zh-HK

**Fixed duplicate for uk-UA and zh-TW**

Thanks to @ArmsAsuncion
http://www.lingoes.net/en/translator/langcode.htm

### CODE REVIEW

**Comment by Oolaruu** [comment]
Looks good
AppVeyor build succeeded

**Comment by Greatliu89** [comment]
only when i use zh my computer can read it (at first start)
 but zh-cn zh_cn zh-..............failed

**Comment by Oolaruu** [comment]
Which language you want to use ?
Which strings are not yet translated ?

**Comment by Greatliu89** [comment]
okay.
not yet translated strings
all the item name   like in
PoGo.NecroBot.CLI\ConsoleEventListener.cs            PokestopLooting item name
PoGo.NecroBot.Logic\Tasks\RecycleItemsTask.cs      Recycleing throw away item name
PoGo.NecroBot.Logic\Utils\Statistics.cs                     "levelup string"and getted item name
PoGo.NecroBot.Logic\State\StateMachine.cs            some error massage
     And does the Gems exist when loot? never get it

**Comment by Oolaruu** [comment]
Check my profile, it had my discord name, i'm here for the next 2 hours.

**Comment by MythHack** [comment]
Someone finally discovered the problem. Before I made were ignored

**Comment by Oolaruu** [comment]
Conflict should be 
zh_CN.json
zh_TW.json

who are not zh-CN.json zh-TW.json

**Comment by Oolaruu** [comment]
Conflicts fixed.

**Comment by Oolaruu** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/4477

**Pull request merged**
