### PR TITLE
Add InnoSetup installer

### PR DESCRIPTION
**Pull request by narfman0**
### Description
In addition to Release.zip, perhaps we could have an installer release to add start icons, uninstall, and related. Attached is a trivial inno setup (common windows foss installer) install script. I don't know how release.zip is made, but this script could be run on that result.

### Testing
1. Compile script from 4.0 extracted Release.zip
2. Execute shortcut from start menu
Verified Logs and temp did not copy over. Ensured app ran (very briefly).

### Note
Pardon I don't know more about process of how release.zip is made, but I'm all ears. Was crazy fast for me to write it but I can make tweaks too! :)

### CODE REVIEW

**Comment by A-Charvin** [comment]
Does the bot really require an Inno setup wizard? The same function can be achieved by simply using an SFX archive mode. It's simple to make an Installer with Inno though. :+1: 
I can help with that if needed though.

**Comment by OuttaControlX** [comment]
sounds excessive tbh.

**Comment by VanStorm** [comment]
I think there is no need for creating an installer- Like @A-Charvin already pointed out, an SFX archive would give us the same experience but imho it works fine as it is.

**Comment by Simpuhl** [comment]
Don't think we need an installer either, but if you want include it as optional part of the release that would be cool. 

Might confuse people on where to find the conf and auth though

**Comment by Platem** [comment]
Maybe adding a shortcut to config in the app start folder would fix that, Simpuhl.

**Comment by NecronomiconCoding** [comment]
Thanks for the work, but we have decided this is too overkill.

**Pull request closed without merging**
