### PR TITLE
Ptc login problem optimization

### PR DESCRIPTION
**Pull request by djdookie**
Trying to solve #3455 
If the ptc login didn't return an ptc authtoken, the user now get's the according feedback and the client should retry after a short time.
Before there was no message, no logging and a standard retry interval of 20 seconds, because no correct exception were caught.
This looked like the application just hanged for the user.

### CODE REVIEW

**Comment by djdookie** [comment]
I did a small modification in submodule FeroxRev/RocketAPI. Build seems to fail because of this.
How can I fix this?

**Comment by Meeplez** [comment]
heres a better one
my pullz r fugged



`            try
            {
            begin:
                await Task.Delay(1000);
                if (_session.Settings.AuthType != AuthType.Google || _session.Settings.AuthType != AuthType.Ptc)
                {
                    await _session.Client.Login.DoLogin();
                }
                else
                {
                    goto begin;

                  //  _session.EventDispatcher.Send(new ErrorEvent
                 //   {
                    //    Message = _session.Translation.GetTranslation(TranslationString.WrongAuthType)
                 //   });
                }
            }`

**Comment by GrimmGringo** [comment]
Implemented manually, will commit momentarily

**Comment by djdookie** [comment]
Thanks. But you should please implement the changes in submodule FeroxRev also, as it is part of my change.

**Pull request closed without merging**
