### PR TITLE
Added Telegram

### PR DESCRIPTION
**Pull request by MineMalox**
I have added Telegram support to the newest Version of NecroBot

Available Commands:
/top <amount> - Shows you top Pokemons. 
/all - Shows you all Pokemons. 
/profile - Shows you profile. 
/loc - Shows you location. 
/items - Shows your items.

### CODE REVIEW

**Comment by uplusion23** [comment]
@MineMalox What exactly is Telegram?

**Comment by Delta1977** [comment]
https://core.telegram.org/bots here you must create an bot  with the api key

**Comment by MineMalox** [comment]
0. You install the Telegram app.
1. You go in your Telegram app and search for the user "BotFather" and start to chat with him.
2. You type /newbot.
3. You give your Bot a Name.
4. Now you have to give you bot a Username ending with "bot" something like: necrobot_bot or necrobot
5. Now you are getting an HTTP API Code with you are adding in the config.json under "TelegramAPIKey"
6. You set UseTelegramAPI to true.
7. Have fun with the BOT!

**Comment by memsenpai** [comment]
how to use it in necrobot ?

**Comment by memsenpai** [comment]
i have api done but i dont know how to use it ? open other cmd ? i can type text on necrobot

**Comment by lucabravi** [comment]
is it possible to add IV in pokemon list /all and /top? 
tks <3

**Comment by aVitomin** [comment]
http://c2n.me/3B12jG7.png

It's correct setiings or no ? Or i need paste only "Key" without bot id ?

**Comment by MineMalox** [comment]
I created an Wiki Page need only an Admin to merge it:

-> https://github.com/MineMalox/NecroBot/wiki/Telegram

**Comment by schwartzadev** [comment]
@MineMalox Added wiki page: https://github.com/NECROBOTIO/NecroBot/wiki/Telegram Thanks

**Comment by nilsbrychzy** [comment]
Hello,

you are using my PR for your PR, but mine was denied. Credits would be nice...

**Comment by nilsbrychzy** [comment]
Here's the proof: #1347

**Comment by TemhAAhmeT** [comment]
Wish to have more commands like /status /level /pause /start etc.

**Pull request merged**
