### PR TITLE
Use berry when pokemon escape and choose how many berries to use per pokemon

### PR DESCRIPTION
**Pull request by cawk**
As title says have tested and works fine

### CODE REVIEW

**Comment by cawk** [comment]
used the berry for each time if they escape from @mrnitrate
i just added the how many berrys to use on a pokemon

**Comment by cawk** [comment]
Just renamed config names for better understanding

**Comment by cawk** [comment]
fixed a debug error i made

**Comment by ThomasSRL** [comment]
Wont this break the softban recognition?
Anyway thanks for adding new features, I just dislike the fact that it always seems to expand the config.

**Comment by cawk** [comment]
no it wont break it because catch escape and catch flee are different things

**Pull request merged**
