### PR TITLE
Bot isnt working.

### PR DESCRIPTION
**Pull request by canuckle604**
Hey this bot stopped working just today i believe. it says there are no pokestops availiable, distance too far. please help!!!

### CODE REVIEW

**Comment by NickTiddy52** [comment]
Same issue

**Comment by cswxin** [comment]
It says,
No usable PokeStops found in your area. Is youe maximum distance too small?

**Comment by canuckle604** [comment]
Yeah, I dont know whats going on i hope this gets fixed soon ;p

**Comment by nevertrustme** [comment]
No usable PokeStops found in your area. Is youe maximum distance too small? same all wotk but nothing  with gps

**Comment by masarmin** [comment]
same problem, hope will fix soon

**Comment by BuloZB** [comment]
Hi all bot don't work because niatic made some changes just wait for update guys

**Comment by pantez** [comment]
Pokemon  Go has new update. Niantic was removed or changed some function which detect pokemon and pokestops.

**Comment by golitsyn** [comment]
https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

**Comment by canuckle604** [comment]
Thanks alot guys!! you guys are quick to respond fast ;p

**Comment by LudZll** [comment]
same here since this morning, cant find pokestops, it says maybe your max distance too small? it 1000 m already, i change it to 10.000 100.0000 still not working, please fix this. waiting for the update

**Comment by jonsnowwatch** [comment]
yeah yeah blah blah, niantic updated their api, just wait a day or two OR how about actually play pokemon go for a change??

**Comment by golitsyn** [comment]
@canuckle604 we are glad to help :D
image

**Comment by LudZll** [comment]
haha yeah youre right, i open the app for now to play while waiting :D

**Comment by MrGermanrain** [comment]
Same here, coordination switches didn't work either. :/

It looks Niantic really want to put a stop on bots.

**Comment by thisKeeWord** [comment]
any updtaes?

**Comment by abaabe10** [comment]
Or you can play Nox.

**Comment by thisKeeWord** [comment]
what is "Nox"?

**Comment by MrGermanrain** [comment]
Another game

**Comment by abaabe10** [comment]
Google "Pokemon Nox"
You can play pokemon go on your pc without going out.

**Comment by thisKeeWord** [comment]
nah. i'll wait?

**Comment by Bociej** [comment]
thisKeeWord go to twitch.tv/grylowanie and enjoy nox. on stream are guides and other sfuff

**Comment by abaabe10** [comment]
what level are you guys?

**Comment by RedSon29** [comment]
Does this mean i have to leave my house now?

**Comment by Bociej** [comment]
20 lvl i started play today and now waiting for bot :D

**Comment by abaabe10** [comment]
level 20 in one day damn

**Comment by Bociej** [comment]
just 7-8 non stop farming hours in 6pokestop spot in mineapolis :P

**Comment by abaabe10** [comment]
Do you guys know of any good pokevision alternatives?

**Comment by gnrendrawijaya** [comment]
guys ,anyone have bot _**just**_ auto transfer pokemon ?

**Comment by fence1247** [comment]
If you have a GPX route, can you run the bot so that it doesn't access the API, but instead just catches pokemon and visits stops as it sees them? 

As I had this thought, I also realized this may not be realistic. I don't know much, but isn't it that bots can't see things the same way we can, and even if they were right on top of a pokestop they wouldn't be able to see it without the API?

**Comment by CaptainKrabb** [comment]
I already tried this, it's the same, there's no error message but nothing happen

**Comment by 977616908** [comment]
Fist at all ，I just want to say thanks to the talented people who are working on reverse engineering right now.Your efforts are appreciated.
Then, i think that they changed  the API  because of they want to enter the Chinese market can only use the map of China.

**Comment by Omigof** [comment]
This what Niatic said,

As many of you know, we recently made some changes to Pokémon GO.
We have removed the ‘3-step’ display in order to improve upon the underlying design. The original feature, although enjoyed by many, was also confusing and did not meet our underlying product goals. We will keep you posted as we strive to improve this feature.

**Comment by Phoenix10King** [comment]
same problem here !!! bot not working, i tried several coords..
so i will make a coffee and i will waiting for the update :P

**Comment by Axod93** [comment]
The same problem. By the way, does anybody know, how to easily copy a config file when updating necrobot? It is hard to copy everything twice a day, keeping up with updates

**Comment by Salapassivfist** [comment]
this shouldnt be a pull request..

**Comment by sithenol** [comment]
PogoLocationFeeder-Release-V0.1.3  still work.
I think bot can work to with a little build.

i hope

**Comment by BenMeitav** [comment]
damn i really need that bot right

**Comment by fujiwaranovan** [comment]
waiting bot working again

**Comment by saint-luciferr** [comment]
@Axod93 this is automatically copied and pasted into the updated config, so no need to worry. @Phoenix10King that is going to be a large coffee.

Rather than everyone posting, i would just be patient and awaiting a response from the wider community as this isn't just effecting those who specifically chose to use this bot but the who communication based on the current API. Be mindful that this isn't a non-trivial change, so it will therefore take a lot longer than usual for this to get reverse engineered.

**Comment by codrin91** [comment]
schermata 2016-08-04 alle 09 07 28
Bot not Work... :(

**Comment by techdude23** [comment]
@codrin91 Read the above posts before posting your own. Everyone has the same issue as you. Niantic force updated their API and everyone's apps. PoGO community devs are currently retrying to reverse engineer and find a workaround.

Source: https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

**Comment by scialbaa** [comment]
Pls stop posting we get it, bot isnt working, just wait or contribute to the workaround..

**Comment by Trish4Mike** [comment]
So I'm guessing there is nothing to do but wait and cross our fingers? Or try playing the game normally...ouch.... I feel lost and stuck at level 29........ sniff sniff

**Comment by yrenegade** [comment]
Hi guys! we are all using ver.0.6.4? it was released 14 hours ago, i didn't understand if the problem persist  ( i've rev 0.5)
thanks

**Comment by koystrubvs** [comment]
Ну что ребят, работа идет?

**Comment by IstenesImre** [comment]
Rush B!

**Comment by cwirek91** [comment]
Could someone update page config from wiki? It should be overcome dispensable questions.

**Comment by Cnuki** [comment]
Hi, i have a problem with config file i want to make the bot to catch all the pokemons no matter on what cp they are and transfer the weaker duplicate one but i dont know how to do it ;/ when i turned on the bot it transferd almost all of my pokemons ;(

**Comment by p0c007** [comment]
@Cnuki until further feedback, please do not use the bot.  it does not work currently and is being investigated.

**Comment by Cnuki** [comment]
@p0c007 i know that bot is in "offline" mod but when its back on i want to have a good config file

**Comment by Trish4Mike** [comment]
Can someone place a link to .5

**Comment by Trish4Mike** [comment]
Natural blonde here needing coordinates for Paris that will work once it's up and running! Heard that is the only place to get Mr.Mime.... I really need this simplified for discombobulated people like myself lol. 
Philadelphia, PA. Here

**Comment by midokigst** [comment]
@Trish4Mike You can find Mr.Mime in anywhere of Europe, example I live in Finland and saw Mr.Mime nearby in Helsinki, didn't find it but it was somewhere here. Great way to get coordinates is using google maps.

**Comment by cwirek91** [comment]
Where can I find Mew, Mewtwo, Moltres, Zapdos, Aricuno?

**Comment by midokigst** [comment]
@cwirek91 Mew and Mewtwo aren't in the game yet, don't know about those others

**Comment by mufclaw** [comment]
@cwirek91 not currently available

**Comment by cwirek91** [comment]
and Ditto? Is he not currently available too?

**Comment by Cnuki** [comment]
@Trish4Mike you can find coordinates for Paris here

**Comment by Trish4Mike** [comment]
Thank you Midokigst

**Comment by gnrendrawijaya** [comment]
i try using pokesnip , but still not working 

image

**Comment by Axod93** [comment]
Guys, every time I update the bot, it makes new auth and config files and I have to make changes in these files every time! How do I make this automatic?

**Comment by lnmtriet93** [comment]
@Axod93 set TransferConfigAndAuthOnUpdate to true

**Comment by cwirek91** [comment]
Where can I find Ditto?

**Comment by Axod93** [comment]
Thank you!!! You are awesome

**Comment by artkzn** [comment]
че, нет рабочих ботов пока?

**Comment by fasdgag** [comment]
@artkzn @koystrubvs  хвое чпый исрахвоглу елара оясмчпый!!! all the people are talking in english, why don't you try to write in english?

**Comment by artkzn** [comment]
@fasdgag  Хочу на русском и буду, че пиндосы пристали

**Comment by Axod93** [comment]
@artkzn епта нах

**Comment by fasdgag** [comment]
@artkzn gl ;)

**Comment by IstenesImre** [comment]
@artkzn Mert hülyevagy szegénykém? :)

**Comment by donik87** [comment]
bot still no work?

**Comment by akgulebubekir** [comment]
We got it, **BOT IS NOT WORKING!!** please stop writing that and write solutions. Someones getting notification on each comment. Please do not disturb them.

**Comment by poutros** [comment]
Please close this. This isn't an issue tracker, stop spamming it. Spam was the reason why the issue tracker was closed in the first place.

**Comment by whatsupyo** [comment]
i guess the ban wave is coming.  they've just tolerated all the bots to find out their specific parameters for anti-cheat measures and detecting methods.

**Pull request closed without merging**
