### PR TITLE
Feature: Using gmaps navigation for a more realistic movesimulation

### PR DESCRIPTION
**Pull request by Kotentopf1337**
User needs to provide a GMaps API Key. Get it in the Google DevConsole (its the directions API)

### CODE REVIEW

**Comment by NecronomiconCoding** [comment]
What about using OSM ?

**Comment by Linewalker** [comment]
I've made a short test some days ago with gmaps an only per webrequest and without any other plugin. You get everything you need with your private api-key in three lines of code, incl. travel time, meters to endpoint and so on.

**Comment by FabryB** [comment]
Why has this been closed?
We are using Google Elevation anyways for Altitude...

**Comment by hilycker** [comment]
At least write something when you close PRs. This seemed like a good idea.

**Pull request closed without merging**
