### PR TITLE
Telegram crash fix, EvolveWhenLuckyEggsMinMet, EvolveAllAboveIV fixed and more

### PR DESCRIPTION
**Pull request by ChemiHatake**
## Description:
Added a new setting: EvolveWhenLuckyEggsMinMet, Only starts evolving when the UseLuckyEggsMinAmount  requirment is met.

Fixed crashes caused by telegram wrong command usage,
*Now shows correct command usage if usage is wrong!*

Now EvolveAllAboveIv works!

## Fixes:
#4528
#4440
#4399
#4258
#4557

### CODE REVIEW

**Comment by vcafezinho** [comment]
@ChemiHatake Yes, thanks again.

**Comment by ChemiHatake** [comment]
@vcafezinho You're most welcome

**Comment by ChemiHatake** [comment]
Do not merge, this is going through testing right now

**Comment by vcafezinho** [comment]
@ChemiHatake What happened man?

**Comment by ChemiHatake** [comment]
@vcafezinho needs debugging

**Comment by GrimmGringo** [comment]
Can you confirm if this is complete and ready for merging?

**Comment by ChemiHatake** [comment]
@GrimmGringo The telegram service works with the release but not with my fork/the repo.
Ill need to test it when someone fixes it

**Comment by GrimmGringo** [comment]
So this does NOT fix telegram?

**Comment by ChemiHatake** [comment]
It fixes 'crashes caused by telegram wrong command usage,'

**Comment by NecronomiconCoding** [comment]
@ChemiHatake have you tried the newest source ? Seems like its crashing, wanna try fix that?

**Comment by GrimmGringo** [comment]
@ChemiHatake Everywhere you've done this, is wrong:
                                session.LogicSettings.WaitForLuckyEggEvolving ||
                                session.LogicSettings.EvolveKeptPokemonsAtStorageUsagePercentage > 00.0)
                              {
                                  await EvolvePokemonTask.Execute(session, cancellationToken);
                              }

It should be:
                                session.LogicSettings.WaitForLuckyEggEvolving ||
                                session.LogicSettings.KeepPokemonsThatCanEvolve)
                              {
                                  await EvolvePokemonTask.Execute(session, cancellationToken);
                              }

**Comment by GrimmGringo** [comment]
@ChemiHatake Also please rename from WaitForLuckyEggEvolving to EvolveWhenLuckyEggsMinMet

**Comment by ChemiHatake** [comment]
@GrimmGringo  @NecronomiconCoding Okay, 
then the wiki needs to be updated

**Comment by ChemiHatake** [comment]
@NecronomiconCoding I believe its caused by the .NET update.
even tried to revert the TelegramService.cs to the original but it still doesn't work

**Comment by vcafezinho** [comment]
@ChemiHatake Just to say thanks for all your hard working. I am really looking forward to have the EvolveWhenLuckyEggsMinMet implemented. Thanks.

**Comment by ChemiHatake** [comment]
The .Net update to 4.6.2 caused this telegram exception.
I've just confirmed.

**Comment by ChemiHatake** [comment]
this is ready!

**Comment by ChemiHatake** [comment]
and I need to work on it again

**Comment by ChemiHatake** [comment]
DAMNIT

**Comment by GrimmGringo** [comment]
It's back to 4.5.2 but still doesn't work.

**Comment by ChemiHatake** [comment]
@GrimmGringo since this (011b5765) commit, it doesn't work

**Pull request closed without merging**
