### PR TITLE
New : Japanese support *Only Pokemon Name #2375

### PR DESCRIPTION
**Pull request by Oolaruu**
Added support to Japanese requested by @B100c #2375
Only Pokemon Name translated

### CODE REVIEW

**Comment by Oolaruu** [comment]
Wait that I change my Windows with japanese support.

**Comment by B100c** [comment]
I  using the language files by default .
It seems display collapses apparently double-byte characters .
If not in English POKESTOP name , display collapses .

**Comment by Oolaruu** [comment]
Could you give me a picture ?
http://prntscr.com/c130cs

**Comment by Oolaruu** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/2496

**Comment by Kyamei** [comment]
i got this error
https://gyazo.com/624237e89de052fa0eb0047effa39c71
maybe this is because "ソ" contains 0x5c in its code?

**Comment by AndreasGilja** [comment]
U GOT enny new bot that works??

Sendt fra min iPhone

Den 5. aug. 2016 kl. 03.54 skrev Oolaruu <notifications@github.com<mailto:notifications@github.com>>:


Closed #2413<https://github.com/NECROBOTIO/NecroBot/pull/2413>.

-

**Comment by B100c** [comment]
Collapse the display of the line that contains the double-byte character set.
Also use the language files in English, this problem occurs if the DBCS is used in POKESTOP name.

For example,
20:19:11 Traveling to Pokestop: Todai temple (62m) (14 seconds)
20:19:11 Traveling to Pokestop: 東大寺 (62m
↑Will no longer be displayed endings

**Comment by B100c** [comment]
[PHOTO](http://s1.gazo.cc/up/204033.png)
Such a problem for even POKESTOP name is an English version.
A similar problem occurs also in the line to the Pokemon name to the Japanese

**Pull request closed without merging**
