### PR TITLE
add /port to Telegram

### PR DESCRIPTION
**Pull request by DBa2016**
## Short Description:
adding "/port <coords>" parameter to Telegram bot, which restarts the bot and ports to target coordinates.

### CODE REVIEW

**Comment by nilsbrychzy** [comment]
Telegram should never be able to control the bot...

The username is the 'password' to the bot and this feature...

I'm against it!

**Comment by nilsbrychzy** [comment]
@GrimmGringo is this your opinion too?

**Comment by nilsbrychzy** [comment]
Or is the password function already within?

**Comment by DBa2016** [comment]
@nilsbrychzy and why exactly should the user (not Telegram itself!) "never be able to control the bot"?

**Comment by nilsbrychzy** [comment]
I mean that !without! password function, there should be no write access only read. But I now saw the password function so it would be fine!

**Comment by theloser** [comment]
@nilsbrychzy Telegram password feature is breaking the bot though. But once it's fixed I see no issue with controlling the bot via telegram commands.

**Comment by DBa2016** [comment]
The "/restart" functionality was already there, it was just undocumented.

**Comment by nilsbrychzy** [comment]
Okay, when there is no issue, I'll spam your bot to restart, because everyone can write to him

**Comment by DBa2016** [comment]
@nilsbrychzy first you need to know the name of the bot. And also - as already said, the functionality to restart is already there for some time, the command was just not appearing in the help text the bot wrote. My PR does not add this functionality, only the "port" functionality.

**Comment by nilsbrychzy** [comment]
I understood this...

Can you make it toggleable? So everyone who want it can enable it.

**Comment by DBa2016** [comment]
Yes, in a later PR. Currently, the bot does not compile anymore on my PC - nuget conflicts with .NET 4.6.2.

**Comment by GrimmGringo** [comment]
This branch has conflicts that must be resolved

**Comment by DBa2016** [comment]
I am parking this for now - Telegram does not work anyway, so this has to wait until Telegram is fixed.

**Pull request closed without merging**
