### PR TITLE
[Feature] Added a better config merging system

### PR DESCRIPTION
**Pull request by Andrerm124**
Fixed conflicts and reimplemented:
Ignore all pokemon not on Sniper Filter
Time for pokestop arrival

### CODE REVIEW

**Comment by Andrerm124** [comment]
I'd really like to have a second opinion on whether my method should be the new standard and whether I should rip out the old implementation.

**Comment by dddbliss** [comment]
If you look in Settings.cs in Logic, around line 482 you will see where we apply a bunch of defaults, if you can verify we no longer need these and can use DefaultValue attributes insteads, that would be awesome.

**Comment by Andrerm124** [comment]
@dddbliss I did what you suggested and it seems to work fine.

I think this method may overwrite a lot of the VersionCheckState code (Specifically TransferConfig())

**Comment by Andrerm124** [comment]
Do not commit, found an issue with fresh installs. Trying to resolve issue.

**Comment by simplyphp** [comment]
Let us know when the issue has been resolved.

**Comment by Andrerm124** [comment]
Already fixed, it's ready for a commit I believe. Unless you can see any issues that is.

**Comment by Andrerm124** [comment]
@simplyphp Could you please commit this request? I'm heading off for the night and won't be able to fix any conflicts that pop up, thanks :)

**Pull request merged**
