### PR TITLE
Updated for Current API situation

### PR DESCRIPTION
**Pull request by techdude23**
I updated the README in accordance to the current API situation with PokeStops.

Please feel free to reword/rephrase/add if there is anything I missed.

### CODE REVIEW

**Comment by thepeople03** [comment]
does that means the bot is working now? :)

**Comment by Nbsloc** [comment]
Nah , mine still doesn't work :(

**Comment by Jordano3710** [comment]
Na doesnt work for me either man

**Comment by mschader** [comment]
This just means, that when this will be submitted, the front page will kindly inform you about the status of the bot and gives you a reddit link with an explanation why it is not working.

**Comment by petrskuta** [comment]
No, it is not working.

**Comment by Bekareth** [comment]
The issue was found by Mila432 : [link](https://github.com/AeonLucid/POGOProtos/issues/131#issuecomment-237475735)

**Comment by Sharke** [comment]
@Bekareth That's an assumption.

**Comment by romeoDo** [comment]
OMG!!, Read the update please. He stated clearly that the bot won't work (for now). Nothing was updated in the bot program.

**Comment by Sharke** [comment]
Rofl. I love how people are asking "does this mean it works now" when all this change is more stating of the obvious that it doesn't work.

**Comment by ultimatescarz** [comment]
sorry to sound like an ass but when one see updated it desperate people sees this it looks like hey I have updated the bot they dont read the whole sentence or they dont want to understand... unfortunately its like Dig Bick when you read fast it becomes you know what..

**Comment by Sharke** [comment]
@ultimatescarz  Point taken. I read Dig Bick wrong probably 5 times. But still people should take a deep breath and just be patient.

**Comment by Bushrouter** [comment]
Hi! I just wondering is it possible to produce by easy correction of the current program code a stable positioning? Just put a character nearby the certain point and let him/her wait for a beast and catch it?
According to the present message of the programme the issue is pokestops location. What possibility to catch pets? In a case if trainer has enough p-balls this algoritm could work anyhow...

**Comment by baldmonkey1** [comment]
i hope the programmers find a way out ;-;

**Comment by hilycker** [comment]
@Bushrouter the issue is with pokemon too

**Comment by poutros** [comment]
Are you guys stupid enough to not know what THE FUCKING REAME.MD IS??? It doesn't change anything is relation to the program's code. Even if it did, you guys would have to compile it yourselves and clearly you would never be able to since you think a mere pull request without an app update can actually do something. Here: https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/d63g28s

**Comment by Nick2400** [comment]
Since location spoofing still works, woudn't it be an idea to disable looking for pokestops and pokemon and just walk around and change the incubators everytime. Logically this should be able to work since my location spoofing on my phone still works. This way we would still be able to breed eggs.

**Comment by poutros** [comment]
@Nick2400 That could risk a ban so it is better not to do it.

**Comment by gianlu696** [comment]
how much time we have to wait for the bot?

**Comment by poutros** [comment]
@gianlu696 Forever. Now wait.

**Pull request merged**
