### PR TITLE
Fixing the Moveset and transferring

### PR DESCRIPTION
**Pull request by abali1**

### CODE REVIEW

**Comment by ChemiHatake** [comment]
Fix the merge conflicts please,
the source code you're using is probably not up to date.
KeepMinLvl was added (and its related to this part of the code).

**Comment by simplyphp** [comment]
This branch has conflicts that must be resolved

**Comment by actislav** [comment]
pls remove pull request you doing something wrong

**Comment by actislav** [comment]
better wait my commit

**Pull request closed without merging**
