### PR TITLE
Add Ability for Missed Throws

### PR DESCRIPTION
**Pull request by KOTR2003**
Added logic to enable missed throws. The console message logic was there, just not implemented as it was set to always catch the pokemon.

Config file has 2 new options:
EnableMissedThrows and ThrowMissPercentage (self explanatory as to what they do)

### CODE REVIEW

**Comment by cawk** [comment]
Do you want me to do this for you seems you are having some issues?

**Comment by KOTR2003** [comment]
@cawk Revert the changes, just realized there was another file to modify too... just hadn't committed it, and of course I am at work and don't have Visual installed on here...

**Comment by cawk** [comment]
yeah you have to commit the api also 
just PR when you fix it ive already tested your code so if any dev notices it just merge it

**Comment by KOTR2003** [comment]
Ah ok, I see you added the 'HitPokemon' to the API, thanks! 

It should all be good then!

**Comment by cawk** [comment]
no i reverted that commit 
since i didnt realise your PR was closed just make a PR to both when you are ready

**Comment by KOTR2003** [comment]
The API still shows the edit committed which is fine. Will (attempt) to make a PR, in before appveyor build errors.

**Pull request closed without merging**
