### PR TITLE
Fix event exception

### PR DESCRIPTION
**Pull request by shcheuk**
## Short Description:
So many exception message floating in the diagnosis and output windows of visual studio....from the event and stataisticAggregator.....

### CODE REVIEW

**Comment by shcheuk** [comment]
seems like accidetally mixed with another pull request........

**Comment by crinq98** [comment]
so what should we do to solve the problem?

**Comment by shcheuk** [comment]
Commit both of them will do.

**Comment by crinq98** [comment]
http://go.microsoft.com/fwlink/?LinkId=780597 download this

**Pull request merged**
