### PR TITLE
[Feature] Automatic Translation Detection

### PR DESCRIPTION
**Pull request by Andrerm124**
Added a new method to pull the system translation when new configs are created. It will then ask the user if they would like to enter a new language code (And then build the config)

- Thanks to @Oolaruu  for the idea and testing

**UPDATED - Again, ideas supplied by @Oolaruu **
Now asks the user if they would like to download/install a new update (When there is one) and will display any new options added to their config.

### CODE REVIEW

**Comment by Oolaruu** [comment]
I am going to update all language files with Pokemon Name (if missing) and Moveset Name included into this pull request. Also I will share pastebin with english template for both so you guys will start to translate even if it's not merged yet.

Stay stunned. :)

**Comment by Oolaruu** [comment]
French language soon fully translated for "PokemonStrings" and "PokemonMovesetStrings"
Starting to add missing PokemonName + MovesetName to other language.
ETA in about 1H now.

**Comment by Oolaruu** [comment]
#2721

**Comment by Oolaruu** [comment]
All langue files now have "PokemonStrings" + "PokemonMovesetStrings"

**Comment by simplyphp** [comment]
This branch has no conflicts with the base branch

**Comment by simplyphp** [comment]
continuous-integration/appveyor/pr — AppVeyor build failed

**Comment by Andrerm124** [comment]
**CLOSED TO REBUILD MY FORK AND PUSH A FRESH COMMIT**

**Pull request closed without merging**
