### PR TITLE
renaming case sensitive file

### PR DESCRIPTION
**Pull request by mercuriete**
Trying to build this project with mono i found an error.

/usr/lib64/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

        CSC: error CS2001: Source file `Event/InventoryListEvent.cs' could not be found

         3 Warning(s)
         1 Error(s)

Event/InventoryListEvent.Cs   should be lowercase.

### CODE REVIEW

**Comment by DBa2016** [comment]
so it builds with Mono? Apart from current API issues - does it work well with Mono?

**Comment by mercuriete** [comment]
@DBa2016 sorry it does not compile right now :cry: 

the folder rocket api compiles properly, the Logic compiles as well but the main project CLI doesn't compile on mono.

I hit this bug all the times:
https://github.com/jbevain/cecil/issues/204

Fody unhandled exception ocurred.
I will issue a bug in a few days if i can't solve the problem.

**Comment by DBa2016** [comment]
I am actually stuck at the level of trying to resolve nuget dependencies... "nuget restore" fails already to complete.... Any idea?

Assumed API issues can be resolved (which I prefer to be positive in) I'd love to make this work under Linux...

**Comment by mercuriete** [comment]
@DBa2016 sorry but for me is working nuget restore.

nuget
NuGet Version: 2.8.7.0
usage: NuGet <command> [args] [options] 

xbuild 
XBuild Engine Version 14.0
Mono, Version 4.4.1.0
Copyright (C) 2005-2013 Various Mono authors

Im a Gentoo linux user using latest mono version available on my distribution.

output of nuget restore:

nuget restore
Installing 'Costura.Fody 1.3.3.0'.
Installing 'log4net 2.0.5'.
Installing 'Fody 1.29.4'.
Installing 'SuperSocket.WebSocket 1.6.6.1'.
Installing 'GeoCoordinate 1.1.0'.
Installing 'Newtonsoft.Json 9.0.1'.
Installing 'SuperSocket 1.6.6.1'.
Installing 'SuperSocket.Engine 1.6.6.1'.
Installing 'Google.Protobuf 3.0.0-beta4'.
Successfully installed 'SuperSocket.WebSocket 1.6.6.1'.
Successfully installed 'Costura.Fody 1.3.3.0'.
Successfully installed 'GeoCoordinate 1.1.0'.
Successfully installed 'Google.Protobuf 3.0.0-beta4'.
Successfully installed 'SuperSocket.Engine 1.6.6.1'.
Successfully installed 'Fody 1.29.4'.
Installing 'EnterpriseLibrary.TransientFaultHandling.Data 6.0.1304.1'.
Installing 'EnterpriseLibrary.TransientFaultHandling 6.0.1304.0'.
Successfully installed 'EnterpriseLibrary.TransientFaultHandling.Data 6.0.1304.1'.
Installing 'GPSOAuthSharp 0.0.5'.
Successfully installed 'GPSOAuthSharp 0.0.5'.
Successfully installed 'EnterpriseLibrary.TransientFaultHandling 6.0.1304.0'.
Successfully installed 'SuperSocket 1.6.6.1'.
Installing 'VarintBitConverter 1.0.0.0'.
Installing 'Microsoft.AspNet.WebApi.Client 5.2.3'.
Successfully installed 'VarintBitConverter 1.0.0.0'.
Installing 'S2Geometry 1.0.1'.
Successfully installed 'S2Geometry 1.0.1'.
Successfully installed 'Newtonsoft.Json 9.0.1'.
Installing 'C5 2.4.5947.17249'.
Successfully installed 'Microsoft.AspNet.WebApi.Client 5.2.3'.
Installing 'Google.Protobuf.Tools 3.0.0-beta3'.
Successfully installed 'log4net 2.0.5'.
Successfully installed 'C5 2.4.5947.17249'.
Successfully installed 'Google.Protobuf.Tools 3.0.0-beta3'.

**Comment by mercuriete** [comment]
@DBa2016 this is a pull request closed.. im not sure if this is the right place to chat about this.
Maybe is better to create an issue to make a discussion about this.

**Pull request merged**
