### PR TITLE
Updated progress bars

### PR DESCRIPTION
**Pull request by GrimmGringo**

### CODE REVIEW

**Comment by poketestup** [comment]
tutuapp updated his crack for control over the pokemon go ( v1.1.1 IOS ) How difficult is to make an application to use this tutuapp crack and play it automatically , equally applicable for "pokemonanywhere" in android ,
note : now you can not quickly reach several pokestops because the system does not allow you to cash prizes,
please is simple, just make an application to take control of another , an application that controls the crack of tutuapp (ios) and pokemonanywhere (android) . Thank you

**Comment by muschter** [comment]
@poketestup That sounds really stupid.

**Comment by poketestup** [comment]
@muschter it is stupid because you can´t understand the idea or is stupid because for you it is imposible to do?, another idea using the tutuapp cracked game can be making an app for recorded steps (record touch in screen), like a windows macro or mozillas macro, just for lvl up with pokestops, not a complete bot, but is something, (tell me if you need an diagram with apples and bunnies)

**Comment by muschter** [comment]
@poketestup I think it's stupid for multiple reasons:

1. There are too many run-on sentences.
2. Your grammar is near impossible to read.

**Comment by poketestup** [comment]
ok, I dont speak english, I am using google translator. thank you anyway,
I'll see if I can get an application to record touch screen, cya

**Comment by poketestup** [comment]
@muschter

**Pull request merged**
