### PR TITLE
Bahasa Indonesia: Fix translations.

### PR DESCRIPTION
**Pull request by awaaas**
English:
Revert translations that doesn't make sense.
Fix typos.

I'm now using the original name for items (Incense, Lucky Egg, Lure and Razz Berry) to avoid confusion, and wait if there's any official translation from the offical app.

---
Bahasa Indonesia:
Mengembalikan terjemahan yang tidak masuk akal.
Memperbaiki kesalahan penulisan.

Sekarang saya pakai nama barang yang asli, supaya tidak membingungkan (Incense, Lucky Egg, Lure, Razz Berry), sembari menunggu terjemahan resmi dari aplikasi resmi kalau ada.

### CODE REVIEW

**Comment by awaaas** [comment]
This also fixed the issues found in #3179 (which is not merged yet as of now)

**Comment by bulubebek** [comment]
looks good. :)

padanan kata sepertinya sudah tepat. just a little correction, "inventory" cannot be translated as "inventori" since it has a different meaning. paling pas mungkin "inventaris". :)

http://kbbi.co.id/arti-kata/inventori

**Comment by KuroHunter13** [comment]
k
please help me...
why  like this????

**Comment by GrimmGringo** [comment]
This branch has conflicts that must be resolved

**Comment by awaaas** [comment]
@bulubebek ok, thanks for the correction.
@GrimmGringo ok, will rebase the upstream, and open another request.

**Pull request closed without merging**
