### PR TITLE
Telegram Update: Added /pokedex

### PR DESCRIPTION
**Pull request by MineMalox**
Changelog:

* Added /pokedex ( See #3833)
* Fixed /top \<cp/iv\>\<amount\>

### CODE REVIEW

**Comment by dfmeier** [comment]
Sorry if I'm wrong but I think you missed the description of the /pokedex command from the Translations.cs - TranslationString.HelpTemplate

**Comment by MineMalox** [comment]
Ohh thanks for the Info

**Comment by dfmeier** [comment]
I don't know the solution but also in the pokemon needed part of the pokedex command:
#0# Name: Translation for pokemon Missingno is missing

I think it would be the best to completely hide it...

**Comment by MineMalox** [comment]
No it's an Easteregg of Pokemon GO

**Comment by dfmeier** [comment]
Sorry to spam you here but I have a problem with the  /top command:
/top iv works fine
/top iv 15 shows by CP not IV (any other number do the same)

**Comment by MineMalox** [comment]
Edit:
`* Fixed /top <cp/iv><amount>`

**Comment by GrimmGringo** [comment]
This branch has conflicts that must be resolved

**Comment by MineMalox** [comment]
Done!

**Comment by NecronomiconCoding** [comment]
fix conflicts, also do not change the translations please

**Comment by MineMalox** [comment]
Why you closed it please? Everything was fine...

**Pull request closed without merging**
