### PR TITLE
Info spam Error

### PR DESCRIPTION
**Pull request by Cx974**
How do I get rid of this info spam?
1be58025eecd6e37e3a8238c6ac39e84

### CODE REVIEW

**Comment by junaidd007** [comment]
bro are the pokestops working?

**Comment by Cx974** [comment]
Nothing is working, literally just spams that the entire time

**Comment by junaidd007** [comment]
image

**Comment by junaidd007** [comment]
the pokestops aren't working

**Comment by junaidd007** [comment]
image

**Comment by romeoDo** [comment]
There have been some changes in Niantic APIs and nothing works at the moment. I doubt if we will ever get the bot running again since the new APIs are all encrypted.

**Comment by junaidd007** [comment]
yeah i think  you are right

**Comment by popoche** [comment]
What really :( ?? it will not be fixed ?

**Comment by thisKeeWord** [comment]
freals? :(
any updates?

**Comment by cr4sh62** [comment]
Just wait and stop asking ... developpers have life too ;)

Niantics do some change and they need to work on this. It's all.

**Comment by poutros** [comment]
This is not an issue tracker, stop spamming it.

**Pull request closed without merging**
